version: '3'
services:
  db:
    image: postgres
    container_name: '${CONTAINER_NAME}'
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    env_file:
      - .env
    volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres: